### ISSUE TITLE
Fatal Exception

### ISSUE THREAD

**Issue by PatrickCrenshaw** [Wordseer/stanford-corenlp-python#2]
I'm getting an error when I try to run corenlp.py 

```
$ python  corenlp/corenlp.py 
java -Xmx3g -cp stanford-corenlp-full-2013-11-12/stanford-corenlp-3.3.0.jar:stanford-corenlp-full-2013-11-12/stanford-corenlp-3.3.0-models.jar:stanford-corenlp-full-2013-11-12/xom.jar:stanford-corenlp-full-2013-11-12/joda-time.jar:stanford-corenlp-full-2013-11-12/jollyday.jar:stanford-corenlp-full-2013-11-12/ejml-0.23.jar edu.stanford.nlp.pipeline.StanfordCoreNLP -props /home/patrick/nlp-features/corenlp-python/corenlp/default.properties
Traceback (most recent call last):                                                                                
  File "corenlp/corenlp.py", line 575, in <module>
    nlp = StanfordCoreNLP(options.corenlp, properties=options.properties, serving=True)
  File "corenlp/corenlp.py", line 430, in __init__
    self._spawn_corenlp()
  File "corenlp/corenlp.py", line 413, in _spawn_corenlp
    self.corenlp.expect("done.", timeout=timeouts[i])  # Load model
  File "/usr/lib/python2.7/dist-packages/pexpect.py", line 1316, in expect
    return self.expect_list(compiled_pattern_list, timeout, searchwindowsize)
  File "/usr/lib/python2.7/dist-packages/pexpect.py", line 1330, in expect_list
    return self.expect_loop(searcher_re(pattern_list), timeout, searchwindowsize)
  File "/usr/lib/python2.7/dist-packages/pexpect.py", line 1401, in expect_loop
    raise EOF (str(e) + '\n' + str(self))
pexpect.EOF: End Of File (EOF) in read_nonblocking(). Exception style platform.
<pexpect.spawn object at 0x8c50fac>
version: 2.4 ($Revision: 516 $)
command: /usr/bin/java
args: ['/usr/bin/java', '-Xmx3g', '-cp', 'stanford-corenlp-full-2013-11-12/stanford-corenlp-3.3.0.jar:stanford-corenlp-full-2013-11-12/stanford-corenlp-3.3.0-models.jar:stanford-corenlp-full-2013-11-12/xom.jar:stanford-corenlp-full-2013-11-12/joda-time.jar:stanford-corenlp-full-2013-11-12/jollyday.jar:stanford-corenlp-full-2013-11-12/ejml-0.23.jar', 'edu.stanford.nlp.pipeline.StanfordCoreNLP', '-props', '/home/patrick/nlp-features/corenlp-python/corenlp/default.properties']
searcher: searcher_re:
    0: re.compile("done.")
buffer (last 100 chars): 
before (last 100 chars): ld not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

after: <class 'pexpect.EOF'>
match: None
match_index: None
exitstatus: 1
flag_eof: True
pid: 18679
child_fd: 4
closed: False
timeout: 60
delimiter: <class 'pexpect.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 8192
ignorecase: False
searchwindowsize: 80
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
```

**Comment by ghost** [comment]
Replicated this error with `java 1.8.0_45`, `pip freeze`

```
Unidecode==0.04.18
argparse==1.2.1
jsonrpclib==0.1.3
pexpect==3.3
wsgiref==0.1.2
```

and directory structure `~/.../stanford-corenlp-python/{corenlp, stanford-corenlp-full-2015-04-20, ...}`

any developments since last year?

**Comment by daimrod** [comment]
Hi,

Just to say that I had the exact same error using stanford-corenlp-full-2015-04-20 until I switch to java 1.8.

Thanks for your work!

**Comment by richardxiong** [comment]
Hello, I encounter the same error using stanford-corenlp-full-2015-04-20. And I'm using java 1.8.0_77:
$ java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)

Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 12:54:16) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> corenlp_dir = "stanford-corenlp-full-2015-04-20"
>>> from corenlp import StanfordCoreNLP
>>> corenlp = StanfordCoreNLP(corenlp_dir)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "corenlp/corenlp.py", line 346, in __init__
    self._spawn_corenlp()
  File "corenlp/corenlp.py", line 335, in _spawn_corenlp
    self.corenlp.expect("\nNLP> ")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pexpect/spawnbase.py", line 321, in expect
    timeout, searchwindowsize, async)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pexpect/spawnbase.py", line 345, in expect_list
    return exp.expect_loop(timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pexpect/expect.py", line 105, in expect_loop
    return self.eof(e)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pexpect/expect.py", line 50, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Empty string style platform.
<pexpect.pty_spawn.spawn object at 0x1028ed150>
command: /usr/bin/java
args: ['/usr/bin/java', '-Xmx3g', '-cp', 'edu.stanford.nlp.pipeline.StanfordCoreNLP', '-props', '/Users/richard_xiong/Documents/DeepLearningMaster/stanford-corenlp-python-master/corenlp/default.properties']
buffer (last 100 chars): ''
before (last 100 chars): 'ld not create the Java Virtual Machine.\r\nError: A fatal exception has occurred. Program will exit.\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 9849
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 8192
ignorecase: False
searchwindowsize: 80
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("
NLP> ")

Could you help me on this?

**Comment by muety** [comment]
Any news about this? I'm getting the same error.

**Comment by vuduc153** [comment]
Just gonna leave this here for future reference.
Got the same issue running the package on Google Colab. I managed to fix the issue using:
```
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
!update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
```
